### PR TITLE
chore(npm): add package lock file

### PR DESCRIPTION
**Pull request by JamesSingleton**
This adds a `package-lock.json` file and removes the `.npmrc` file that had `package-lock=false` in it.

Furthermore, the reason there is an update to the test snapshots is because of the following:

```
      // exports
      exports.locals = {
    -   "isUsed": "styles__isUsed___3xJqg"
    +   "isUsed": "styles__isUsed___3gAAa"
      };"
```
For some reason when I did `npm i` and it ran `npm test` is gave me that mismatch so I updated the snapshot. Also, once updated, the `npm i` resulted in `found 68 vulnerabilities (66 low, 1 moderate, 1 high)`

Furthermore, running `npm outdated` results in the following:

| Package            | Current | Wanted  | Latest       |
|--------------------|---------|---------|--------------|
| amex-jest-preset   | 4.4.0   | 4.4.0   | 5.0.0        |
| babel-eslint       | 8.2.6   | 8.2.6   | 10.0.3       |
| babel-loader       | 7.1.5   | 7.1.5   | 8.0.6        |
| css-loader         | 0.28.11 | 0.28.11 | 3.4.2        |
| eslint             | 4.19.1  | 4.19.1  | 6.8.0        |
| eslint-config-amex | 7.1.1   | 7.1.1   | 11.1.0       |
| husky              | 3.1.0   | 3.1.0   | 4.0.10       |
| jest               | 22.4.4  | 22.4.4  | 24.9.0       |
| memory-fs          | 0.4.1   | 0.4.1   | 0.5.0        |
| purgecss           | 0.21.0  | 0.21.0  | 2.0.1-beta.0 |
| style-loader       | 0.21.0  | 0.21.0  | 1.1.2        |

### CODE REVIEW

**Comment by JamesSingleton** [comment]
So it is failing due to the snapshot I updated. At first, I thought it was because I had Node 13.6.0 on my machine. However, after downgrading to 12.14.1 my snapshot does not change. I am wondering if this is a Linux/Mac vs Windows issue.

**Comment by anescobar1991** [comment]
Yeah might be a Windows vs Linux/Mac issue. Can you run on your mac to see?

**Comment by JamesSingleton** [comment]
@anescobar1991 I cloned this on my mac and ran `npm i` and got

```
 // exports
      exports.locals = {
    -   "isUsed": "styles__isUsed___3gAAa"
    +   "isUsed": "styles__isUsed___3xJqg"
      };"
```

So it looks like it is a Windows vs Linux/Mac issue

**Comment by JamesSingleton** [comment]
I removed the snapshot due to there being a diff between Windows and Mac OS and since there are two checks beforehand I think that should suffice.

**Comment by 10xLaCroixDrinker** [comment]
While I'd rather keep the snapshot, if its inconsistent we can drop it. I think the `.toContain` and `.not.toContain` should cover it

**Pull request merged**
